/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/layout`; params?: Router.UnknownInputParams; } | { pathname: `/admin/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/admin/relatorio`; params?: Router.UnknownInputParams; } | { pathname: `/auth/layout`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/morador/historico`; params?: Router.UnknownInputParams; } | { pathname: `/morador`; params?: Router.UnknownInputParams; } | { pathname: `/morador/layout`; params?: Router.UnknownInputParams; } | { pathname: `/morador/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/porteiro`; params?: Router.UnknownInputParams; } | { pathname: `/porteiro/layout`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/relatorio`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/morador/historico`; params?: Router.UnknownOutputParams; } | { pathname: `/morador`; params?: Router.UnknownOutputParams; } | { pathname: `/morador/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/morador/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/porteiro`; params?: Router.UnknownOutputParams; } | { pathname: `/porteiro/layout`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/layout${`?${string}` | `#${string}` | ''}` | `/admin/perfil${`?${string}` | `#${string}` | ''}` | `/admin/relatorio${`?${string}` | `#${string}` | ''}` | `/auth/layout${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/morador/historico${`?${string}` | `#${string}` | ''}` | `/morador${`?${string}` | `#${string}` | ''}` | `/morador/layout${`?${string}` | `#${string}` | ''}` | `/morador/perfil${`?${string}` | `#${string}` | ''}` | `/porteiro${`?${string}` | `#${string}` | ''}` | `/porteiro/layout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/layout`; params?: Router.UnknownInputParams; } | { pathname: `/admin/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/admin/relatorio`; params?: Router.UnknownInputParams; } | { pathname: `/auth/layout`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/morador/historico`; params?: Router.UnknownInputParams; } | { pathname: `/morador`; params?: Router.UnknownInputParams; } | { pathname: `/morador/layout`; params?: Router.UnknownInputParams; } | { pathname: `/morador/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/porteiro`; params?: Router.UnknownInputParams; } | { pathname: `/porteiro/layout`; params?: Router.UnknownInputParams; };
    }
  }
}
